language: python
dist: xenial
os: linux
# arch:
#  - amd64
#  - ppc64le
#  - arm64
python:
  - "nightly"
  - "3.9-dev"
  - "3.8"
  - "3.7"
  - "3.6"
  - "pypy3"
  # - "3.9"
  # 3.9 doesn't exist yet.


# branches:
#   only:
#   - master

before_install:
  - python3 -m pip install wheel
  - python3 -m pip install poetry

install:
  - poetry install --no-root
  - poetry lock

cache: pip
jobs:
    allow_failures:
     - python: "pypy3"
     - python: "nightly"
script:
  - poetry run pytest tests/ -vvv --durations=3  --cov=src --cov-report=xml
  - poetry build
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    on_success: change # default: change
    on_failure: always # default: always
# before_deploy:
#  - make clean
# deploy:
#   provider: pypi
#   username: __token__
#   password:
#     secure: pypi-your_token_here
#   distributions: "sdist bdist_wheel"
#   skip_existing: true
#   on:
#     branch:
#       - master
git:
  quiet: true
