name: linter

on: [push, pull_request]
jobs:
  "Flake8":
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.0"

      - name: Run flake8
        uses: julianwachholz/flake8-action@v1.1.0
        with:
          checkName: "Python Lint"
          path: .
  "MyPy":
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.0"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip poetry
          poetry install --no-root
          poetry lock
      - name: Lint with MyPy
        run: |
          poetry run mypy src
  "Bandit":
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jpetrucciani/bandit-check@master

  "Black":  # For formatting python files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.0"
      - uses: psf/black@stable

  "Isort":
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - uses: actions/setup-python@v2
          with:
            python-version: "3.9.0"
        - name: Install isort
          run: |
            python3 -m pip install isort
        - name: Lint with Isort
          run: python3 -m isort . --check --diff
  "Pylint":
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - uses: actions/setup-python@v2
          with:
            python-version: "3.9.0"
        - name: Install Pylint
          run: |
            python3 -m pip install poetry
            poetry install --no-root
            poetry lock

        - name: Lint with Pylint
          run: poetry run pylint src/**
