name: linter

on: [push, pull_request]
jobs:
  "Flake8":
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.0"

      - name: Run flake8
        uses: julianwachholz/flake8-action@v1.1.0
        with:
          checkName: "Python Lint"
          path: .
  "MyPy":
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.0"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip mypy wheel setuptools
          python3 -m pip install -r requirements.txt
      - name: Lint with MyPy
        run: |
          python3 -m mypy src
          [ -d ./bin ] && python3 -m mypy bin || echo "No .pyi files found in /bin"
  "Bandit":
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Security check - Bandit
        uses: Joel-hanson/bandit-report-artifacts@v1
        with:
          python_version: "3.9.0"
          project_path: .
      - name: Security check report artifacts
        uses: actions/upload-artifact@v1
        # if: failure()
        with:
          name: Security report
          path: output/security_report.txt

  "Black":  # For formatting python files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.0"
      - uses: psf/black@stable

  "Isort":
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - uses: actions/setup-python@v2
          with:
            python-version: "3.9.0"
        - name: Install Isort
          run: |
            python3 -m pip install isort[requirements_deprecated_finder]
        - name: Lint with Isort
          run: python3 -m isort --check-only --diff .
  "Pylint":
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - uses: actions/setup-python@v2
          with:
            python-version: "3.9.0"
        - name: Install Pylint
          run: |
            python3 -m pip install wheel pylint
            python3 -m pip install -r requirements.txt
        - name: Lint with Pylint
          run: python3 -m pylint src/**
