name: linter

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  "Flake8":
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.0"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip flake8 wheel setuptools
          python3 -m pip install -r requirements.txt
      - name: Lint with flake8
        run: python3 -m flake8 .
  "MyPy":
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.0"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip mypy wheel setuptools
          python3 -m pip install -r requirements.txt
      - name: Lint with MyPy
        run: |
          python3 -m mypy src
          [ -d ./bin ] && python3 -m mypy bin || echo "No .pyi files found in /bin"
  "Bandit":
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.0"
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip bandit wheel setuptools
          python3 -m pip install -r requirements.txt
      - name: Lint with Bandit
        run: bandit -r .

  "Black":  # For formatting python files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.0"

      - name: Install black
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install black

      # The fun stuff
      - name: Blacken
        run: python3 -m black .

  "Isort":
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Install isort
          run: |
            python3 -m pip install --upgrade pip
            python3 -m pip install isort

        # The fun stuff
        - name: Isort
          run: python3 -m isort .
