name: PythonCI

# Pypi upload and coverage covered in Travis-CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  "pytest-Ubuntu":
    strategy:
      matrix:
        python-version:  # 3.6 to 3.9
         - "3.9.0"
         - "3.8.5"
         - "3.8.4"
         - "3.8.3"
         - "3.8.2"
         - "3.8.1"
         - "3.8.0"
         - "3.7.9"
         - "3.7.8"
         - "3.7.7"
         - "3.7.6"
         - "3.7.5"
         - "3.6.12"
         - "3.6.11"
         - "3.6.10"
         - "3.6.9"
         - "3.6.8"
         - "3.6.7"
        os:
         - "ubuntu-latest"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/bot-tester-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip
            ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/bot-tester-requirements.txt') }}-2
            ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
            ${{ runner.os }}-pip-${{ hashFiles('**/bot-tester-requirements.txt') }}
            ${{ runner.os }}-pip-key
            ${{ runner.os }}-
            ${{ runner.os }}-restore
            ${{ runner.os }}-restore-pip
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt bot-tester-requirements.txt
      - name: Test with pytest
        run: |
          make test || pytest tests/ -vvv --durations=3
  "pytest-MacOS":
    strategy:
      matrix:
        python-version:  # 3.6 to 3.9
         - "3.9.0"
         - "3.8.5"
         - "3.8.4"
         - "3.8.3"
         - "3.8.2"
         - "3.8.1"
         - "3.8.0"
         - "3.7.9"
         - "3.7.8"
         - "3.7.7"
         - "3.7.6"
         - "3.7.5"
         - "3.6.12"
         - "3.6.11"
         - "3.6.10"
         - "3.6.9"
         - "3.6.8"
         - "3.6.7"
        os:
         - "macos-latest"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
      - uses: actions/cache@v2
        with:
          path: ~/Library/Caches/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/bot-tester-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip
            ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/bot-tester-requirements.txt') }}-2
            ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
            ${{ runner.os }}-pip-${{ hashFiles('**/bot-tester-requirements.txt') }}
            ${{ runner.os }}-pip-key
            ${{ runner.os }}-
            ${{ runner.os }}-restore
            ${{ runner.os }}-restore-pip
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r bot-tester-requirements.txt
          python3 -m pip install -r requirements.txt bot-tester-requirements.txt
      - name: Test with pytest
        run: |
          make test || pytest tests/ -vvv --durations=3
  "pytest-Windows":
    strategy:
      matrix:
        python-version:  # 3.6 to 3.9
         - "3.9.0"
         - "3.8.3"
         - "3.8.2"
         - "3.8.1"
         - "3.8.0"
         - "3.7.9"
         - "3.7.7"
         - "3.7.6"
         - "3.6.8"
         - "3.6.7"
        os:
         - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v2
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/bot-tester-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip
            ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/bot-tester-requirements.txt') }}-2
            ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
            ${{ runner.os }}-pip-${{ hashFiles('**/bot-tester-requirements.txt') }}
            ${{ runner.os }}-pip-key
            ${{ runner.os }}-
            ${{ runner.os }}-restore
            ${{ runner.os }}-restore-pip
      - name: Install dependencies
        run: |
          python -m pip install --no-warn-script-location --upgrade pip
          python -m pip install  --no-warn-script-location -r requirements.txt bot-tester-requirements.txt
      - name: Test with pytest
        run: |
          make test || pytest tests/ -vvv --durations=3
  "flake8":
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.0"
      - uses: actions/cache@v2
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip
            ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-2
            ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
            ${{ runner.os }}-pip-key
            ${{ runner.os }}-
            ${{ runner.os }}-restore
            ${{ runner.os }}-restore-pip
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip flake8
          python3 -m pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          python3 -m flake8 .
  "mypy":
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.0"
      - uses: actions/cache@v2
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip
            ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-2
            ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
            ${{ runner.os }}-pip-key
            ${{ runner.os }}-
            ${{ runner.os }}-restore
            ${{ runner.os }}-restore-pip
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip mypy
      - name: Mypy
        run: |
          python3 -m mypy --strict --namespace-packages src
          [ -d ./bin ] && python3 -m mypy --strict --namespace-packages bin || echo "No .pyi files found in /bin"
