name: PythonCI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  "pytest (Ubuntu)":
    strategy:
      matrix:
        python-version:  # 3.6 to 3.9
         - "3.9.0-rc.1"
         - "3.9.0-beta.5"
         - "3.9.0-beta.4"
         - "3.8.5"
         - "3.8.4"
         - "3.8.3"
         - "3.8.2"
         - "3.8.1"
         - "3.8.0"
         - "3.7.9"
         - "3.7.8"
         - "3.7.7"
         - "3.7.6"
         - "3.7.5"
         - "3.6.12"
         - "3.6.11"
         - "3.6.10"
         - "3.6.9"
         - "3.6.8"
         - "3.6.7"
        os:
         - "ubuntu-latest"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/dev-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip
            ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/dev-requirements.txt') }}-2
            ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
            ${{ runner.os }}-pip-${{ hashFiles('**/dev-requirements.txt') }}
            ${{ runner.os }}-pip-key
            ${{ runner.os }}-
            ${{ runner.os }}-restore
            ${{ runner.os }}-restore-pip
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pytest pytest-cov
          python3 -m pip install -r requirements.txt
      - name: Test with pytest
        run: |
          make test || pytest tests/ -vvv --durations=3 --cov=src/package_name
      - name: Codecov Upload
        run: curl -s https://codecov.io/bash | bash
  "pytest (MacOS)":
    strategy:
      matrix:
        python-version:  # 3.6 to 3.9
         - "3.9.0-rc.1"
         - "3.9.0-beta.5"
         - "3.9.0-beta.4"
         - "3.8.5"
         - "3.8.4"
         - "3.8.3"
         - "3.8.2"
         - "3.8.1"
         - "3.8.0"
         - "3.7.9"
         - "3.7.8"
         - "3.7.7"
         - "3.7.6"
         - "3.7.5"
         - "3.6.12"
         - "3.6.11"
         - "3.6.10"
         - "3.6.9"
         - "3.6.8"
         - "3.6.7"
        os:
         - "macos-latest"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
      - uses: actions/cache@v2
        with:
          path: ~/Library/Caches/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/dev-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip
            ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/dev-requirements.txt') }}-2
            ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
            ${{ runner.os }}-pip-${{ hashFiles('**/dev-requirements.txt') }}
            ${{ runner.os }}-pip-key
            ${{ runner.os }}-
            ${{ runner.os }}-restore
            ${{ runner.os }}-restore-pip
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pytest pytest-cov
          python3 -m pip install -r requirements.txt
      - name: Test with pytest
        run: |
          make test || pytest tests/ -vvv --durations=3 --cov=src/package_name
      - name: Codecov Upload
        run: curl -s https://codecov.io/bash | bash
  "pytest (Windows)":
    strategy:
      matrix:
        python-version:  # 3.6 to 3.9
         - "3.9.0-rc.1"
         - "3.9.0-beta.5"
         - "3.9.0-beta.4"
         - "3.8.5"
         - "3.8.4"
         - "3.8.3"
         - "3.8.2"
         - "3.8.1"
         - "3.8.0"
         - "3.7.9"
         - "3.7.8"
         - "3.7.7"
         - "3.7.6"
         - "3.7.5"
         - "3.6.12"
         - "3.6.11"
         - "3.6.10"
         - "3.6.9"
         - "3.6.8"
         - "3.6.7"
        os:
         - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
      - uses: actions/cache@v2
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/dev-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip
            ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/dev-requirements.txt') }}-2
            ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
            ${{ runner.os }}-pip-${{ hashFiles('**/dev-requirements.txt') }}
            ${{ runner.os }}-pip-key
            ${{ runner.os }}-
            ${{ runner.os }}-restore
            ${{ runner.os }}-restore-pip
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pytest pytest-cov
          python3 -m pip install -r requirements.txt
      - name: Test with pytest
        run: |
          make test || pytest tests/ -vvv --durations=3 --cov=src/package_name
      - name: Codecov Upload
        run: curl -s https://codecov.io/bash | bash
  "flake8":
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/dev-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip
            ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/dev-requirements.txt') }}-2
            ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
            ${{ runner.os }}-pip-${{ hashFiles('**/dev-requirements.txt') }}
            ${{ runner.os }}-pip-key
            ${{ runner.os }}-
            ${{ runner.os }}-restore
            ${{ runner.os }}-restore-pip
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install flake8
          python3 -m pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          python3 -m flake8 . --count --show-source --statistics --max-complexity=20
